# Point to the public directory of your Symfony project
index index.php index.html;

location / {
    # try to serve file directly, fallback to index.php
    try_files $uri /index.php$is_args$args;
}

# PROD, DEV, or STAGE environment routing
location ~ ^/index\.php(/|$) {
    # Pass the request to PHP-FPM
    fastcgi_pass unix:/run/php-fpm/www.sock; # 127.0.0.1:9000;
    fastcgi_split_path_info ^(.+\.php)(/.*)$;
    include /etc/nginx/fastcgi_params;

    # By default, the PHP-FPM script_filename is root + fastcgi_script_name
    fastcgi_param SCRIPT_FILENAME $document_root$fastcgi_script_name;
    fastcgi_param DOCUMENT_ROOT $document_root;

    # Prevents URIs that include the front controller being incorrectly routed
    internal;
}

# Return 404 for all other php files not matching the front controller
location ~ \.php$ {
    return 404;
}
